from __future__ import annotations

import json
from datetime import date
import logging
from typing import Any, Dict, List, TypedDict

from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph
from langchain_core.messages import HumanMessage, SystemMessage

from .config import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)


class RecipeState(TypedDict, total=False):
    target_date: str
    country_code: str
    recipe_count: int
    prompt: str
    raw_response: str
    recipes: List[Dict[str, Any]]


def _build_prompt(state: RecipeState) -> RecipeState:
    count = state["recipe_count"]
    country = state.get("country_code", "BG")
    cuisine = "Greek" if country == "GR" else "Bulgarian"
    
    prompt = f"""You are a culinary assistant specializing in {cuisine} weeknight cooking.
Generate {count} distinct {cuisine} recipes that:
- are realistic to prepare on a weeknight (total prep + cook time must be 20-45 minutes)
- highlight regional flavors and traditional techniques
- each use exactly one primary protein source (for example: chicken, pork, beef, lamb, fish, beans)
- never repeat the same protein across recipes for the same day
- list ingredients with precise metric quantities
- provide clear, actionable step-by-step cooking instructions
- include a concise summary explaining why the dish fits a busy evening.

Respond with minified JSON using this schema exactly:
{{
  "recipes": [
    {{
      "title": "string",
      "summary": "string",
      "protein": "string",
      "meal_type": "breakfast|lunch|dinner",
      "serves": integer (2-6),
      "prep_time_minutes": integer (5-25),
      "cook_time_minutes": integer (5-30),
      "ingredients": [
        {{
          "name": "ingredient name",
          "quantity": "metric quantity like '150 g' or '2 tsp'"
        }}
      ],
      "instructions": ["step 1", "step 2", "..."]
    }}
  ]
}}

Ensure prep_time_minutes + cook_time_minutes <= 45.
Target date: {state['target_date']}
"""
    return {"prompt": prompt, **state}


def _flatten_content(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: List[str] = []
        for item in content:
            if isinstance(item, dict):
                if "text" in item:
                    parts.append(str(item["text"]))
                elif "type" in item and item["type"] == "output_text":
                    parts.append(str(item.get("text", "")))
                else:
                    parts.append(str(item))
            else:
                parts.append(str(item))
        return "".join(parts)
    return str(content)


def _call_llm(state: RecipeState) -> RecipeState:
    if not settings.openai_api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not configured. Set it before generating recipes."
        )

    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0.6,
        max_tokens=2000,
        openai_api_key=settings.openai_api_key,
        model_kwargs={"response_format": {"type": "json_object"}},
    )
    messages = [
        SystemMessage(
            content="You are an expert Balkan chef who writes concise, structured recipes."
        ),
        HumanMessage(content=state["prompt"]),
    ]
    response = llm.invoke(messages)
    raw = _flatten_content(response.content)
    logger.debug("LLM raw response: %s", raw)
    return {"raw_response": raw, **state}


def _parse_response(state: RecipeState) -> RecipeState:
    raw = state["raw_response"].strip()
    if raw.startswith("```"):
        segments = raw.split("```")
        for segment in segments:
            segment = segment.strip()
            if not segment:
                continue
            if segment.lower().startswith("json"):
                segment = segment[4:].strip()
            raw = segment
            break
    if not raw:
        raise ValueError("Model returned an empty response.")
    trimmed_raw = raw
    if not raw.strip().startswith("{"):
        start = raw.find("{")
        end = raw.rfind("}")
        if start != -1 and end != -1 and end > start:
            trimmed_raw = raw[start : end + 1]
    try:
        payload = json.loads(trimmed_raw)
    except json.JSONDecodeError as exc:
        logger.error("Invalid JSON from model: %s", raw)
        raise ValueError("Model returned invalid JSON") from exc

    recipes = payload.get("recipes", [])
    if not isinstance(recipes, list) or not recipes:
        raise ValueError("No recipes were generated by the model.")

    return {"recipes": recipes, **state}


graph = StateGraph(RecipeState)
graph.add_node("build_prompt", _build_prompt)
graph.add_node("generate", _call_llm)
graph.add_node("parse", _parse_response)
graph.set_entry_point("build_prompt")
graph.add_edge("build_prompt", "generate")
graph.add_edge("generate", "parse")
graph.add_edge("parse", END)

compiled_graph = graph.compile()


def generate_recipes_for_date(target_date: date, recipe_count: int, country_code: str = "BG") -> List[Dict[str, Any]]:
    """Run the LangGraph pipeline to create recipes for a specific date."""
    state_input: RecipeState = {
        "target_date": target_date.isoformat(),
        "country_code": country_code,
        "recipe_count": recipe_count,
    }
    result = compiled_graph.invoke(state_input)
    return result["recipes"]
